import type { PlaylistConfig } from './sermons'

export const YOUTUBE_CHANNEL_ID = 'UCgI1-OGVDlM5cXy0xhllT_w'
export const SPOTIFY_SHOW_ID = '7AZydPQgOQOqdvpiXLGyRR'

// Apple Podcasts collection id for "NJ Mosaic Christian Fellowship".
export const APPLE_PODCAST_ID = '1440078295'
export const APPLE_PODCAST_SHOW_URL =
  'https://podcasts.apple.com/us/podcast/nj-mosaic-christian-fellowship/id1440078295'

// kind:
//   'master'   — the full pool of candidate videos; always exactly one
//   'series'   — sermon series; videos surface in the archive AND group under the series
//   'excluded' — clips/promos/non-sermons; dropped from the archive entirely
//   'category' — routed out of the sermon archive into its own collection and
//                page, keyed by `slug`. Unlike 'excluded' the videos are kept.
//
// The master is the channel's UPLOADS playlist (`UU` + the channel id minus `UC`). It is
// generated by YouTube, cannot be deleted, and always contains every public upload.
// A hand-curated master used to fill this role and was deleted during the church's
// 2026-07-01 channel reorganisation, which broke the sermon sync silently — every sync
// threw on a 404 and no sermon had been added since. Do not point this at a hand-made
// playlist again: a master that a channel admin can delete is a single point of failure.
//
// Because the master admits everything, curation happens in the 'excluded' list below,
// which mirrors the playlists the church itself maintains as non-preaching. Staff can
// reclassify a video by moving it between playlists in YouTube — no code change needed.
export const PLAYLISTS: PlaylistConfig[] = [
  { id: 'UUgI1-OGVDlM5cXy0xhllT_w', name: 'Channel uploads', kind: 'master' },

  // Non-sermon content. 'Non-Sermon Series (YYYY)' are the church's own labels.
  { id: 'PLTE5RdzlAcPU', name: 'End of Year Recap Videos', kind: 'excluded' },
  { id: 'PLcVnilxMSYGIBRluW_HNkB3oVLzn2rVqa', name: 'Highlights!', kind: 'excluded' },
  { id: 'PLf6zW0LhpFkc', name: 'Let\'s Talk', kind: 'excluded' },
  { id: 'PLXScyIQngEbc', name: 'Non-Sermon Series (2021)', kind: 'excluded' },
  { id: 'PLMcS9_NrCS4M', name: 'Non-Sermon Series (2023)', kind: 'excluded' },
  { id: 'PLUwHa_RG4DTQ', name: 'Non-Sermon Series (2024)', kind: 'excluded' },
  { id: 'PLLk3Ze_LUBWg', name: 'Non-Sermon Series (2025)', kind: 'excluded' },
  { id: 'PLcVnilxMSYGLxElwnvRqRXmlAyH4jHi42', name: 'See You Sunday', kind: 'excluded' },
  { id: 'PLfCPBDaKai00', name: 'Seminars', kind: 'excluded' },
  { id: 'PLcVnilxMSYGLZdeUjrCE8ZPDlLZu6zOEC', name: 'Sermon Clips', kind: 'excluded' },
  { id: 'PLcVnilxMSYGJ9aPoAOxqP6VE1RtAPQnOw', name: 'Testimonies', kind: 'category', slug: 'testimonies' },
  { id: 'PLSyuqxO2rE7s', name: 'Welcome to Mosaic!', kind: 'excluded' },

  // Sermon series, newest first. Adding a new series here is optional — an unlisted
  // series still appears in the archive, it just shows no series name.
  { id: 'PLa7MUUaBoWM4', name: 'Different by Design (2026)', kind: 'series' },
  { id: 'PLG6ycQOcF6LA', name: 'Family Series (2026)', kind: 'series' },
  { id: 'PLJ9zQKneZnJ8', name: 'Holy Week Consecrate & Easter (2026)', kind: 'series' },
  { id: 'PLGxoIkT6QRl0', name: 'Mosaic Vision Series (2026)', kind: 'series' },
  { id: 'PLcVnilxMSYGLTHy8xjdb3CaIB0axomgxd', name: 'The God of Promise (2026)', kind: 'series' },
  { id: 'PLI4jKi9SCPLc', name: 'Unshaken Faith (2026)', kind: 'series' },
  { id: 'PLYul7S3Q4m4k', name: '1 Thessalonians (2025)', kind: 'series' },
  { id: 'PLDl3KhJZdQ-8', name: 'Advent & New Years Eve (2025)', kind: 'series' },
  { id: 'PLcVnilxMSYGI3tJD8kfKVO8JdTDuw416N', name: 'Healing, Anchoring, Thriving (2025)', kind: 'series' },
  { id: 'PLKjuun3vlVUc', name: 'Holy Week Consecrate & Easter (2025)', kind: 'series' },
  { id: 'PLOnz-mzXgTP0', name: 'Missions Month (2025)', kind: 'series' },
  { id: 'PLOzuzO5YDkjA', name: 'Mosaic Vision Series (2025)', kind: 'series' },
  { id: 'PLYDsYYw1YC18', name: 'Nehemiah (2025)', kind: 'series' },
  { id: 'PLD_nH7f2HsPM', name: 'Unfamiliar Prophets (2025)', kind: 'series' },
  { id: 'PLYGZgP4MNkzM', name: 'Advent & New Years Eve (2024)', kind: 'series' },
  { id: 'PLQITjbKVnt6E', name: 'Consecrate Holy Week (2024)', kind: 'series' },
  { id: 'PLLGSE5sfHUGc', name: 'Family Series (2024)', kind: 'series' },
  { id: 'PLf5F-jvWPyhU', name: 'Holy Week Consecrate & Easter (2024)', kind: 'series' },
  { id: 'PLWXgtIhUMlyw', name: 'Life in the Spirit (2024)', kind: 'series' },
  { id: 'PLaM1vaCuCtnk', name: 'Missions Month (2024)', kind: 'series' },
  { id: 'PLKyLHz1fl-wU', name: 'Mosaic Vision Series (2024)', kind: 'series' },
  { id: 'PLcal0yONxVxU', name: 'Realign (2024)', kind: 'series' },
  { id: 'PLSqnYMYZ-eTc', name: 'Victory Reimagined: Joshua (2024)', kind: 'series' },
  { id: 'PLMGRL4ZFRW10', name: 'Advent & New Years Eve (2023)', kind: 'series' },
  { id: 'PLYNdXsSeXsLg', name: 'Family Series (2023)', kind: 'series' },
  { id: 'PLB9gSTDKU_lE', name: 'Great Faith (2023)', kind: 'series' },
  { id: 'PLfvHkNjYHdIQ', name: 'Holy Week Consecrate & Easter (2023)', kind: 'series' },
  { id: 'PLSl2an-2snc8', name: 'Missions Month (2023)', kind: 'series' },
  { id: 'PLNcK-9YE-Fas', name: 'Mosaic Vision Series (2023)', kind: 'series' },
  { id: 'PLPE_S_FZOWgk', name: 'Reconnecting with God: Psalms (2023)', kind: 'series' },
  { id: 'PLJlTufgtJg_c', name: 'The Unforgotten Church (2023)', kind: 'series' },
  { id: 'PLYNttBQCGfj8', name: 'Christmas (2022)', kind: 'series' },
  { id: 'PLcVnilxMSYGJ1peaxVCbERsviSnNHrqZU', name: 'Community (2022)', kind: 'series' },
  { id: 'PLVGvO8G1YnoY', name: 'Consecrate Holy Week (2022)', kind: 'series' },
  { id: 'PLUNfqU1TR3x8', name: 'Discipleship (2022)', kind: 'series' },
  { id: 'PLcVnilxMSYGJDSH5-Des6MbXJToUeEuwO', name: 'Hebrews (2022)', kind: 'series' },
  { id: 'PLMi20rrQBXpo', name: 'Holy Week Consecrate (2022)', kind: 'series' },
  { id: 'PLcVnilxMSYGJbMQwmKoeiT4g8SCJI8_Md', name: 'Jeremiah: Return to the Promise (2022)', kind: 'series' },
  { id: 'PLbprPDypTTZo', name: 'Missions Month (2022)', kind: 'series' },
  { id: 'PLcVnilxMSYGK7QtZXH3YQgDakfolV9U32', name: 'Serving Series (2022)', kind: 'series' },
  { id: 'PLbOH4US-Tw0k', name: 'Advent & New Years Eve (2021)', kind: 'series' },
  { id: 'PLECJkxJ_z9Cs', name: 'Church Reclaimed (2021)', kind: 'series' },
  { id: 'PLMh4Ot45dyVI', name: 'Gospel Clarity (2021)', kind: 'series' },
  { id: 'PLaxrd2yJUuEU', name: 'Salt & Light (2021)', kind: 'series' },
  { id: 'PLa-GlOEGxJeI', name: 'The Book of James (2021)', kind: 'series' },
  { id: 'PLMCPCoi_qtzg', name: 'The Wedding Supper of the Lamb (2021)', kind: 'series' },
  { id: 'PLJmS7BXn341o', name: 'Christmas (2020)', kind: 'series' },
  { id: 'PLbR3iNZ3rgSI', name: 'Emotionally Healthy Spirituality (2020)', kind: 'series' },
  { id: 'PLciR4CFSN74o', name: 'Mosaic Vision Series (2020)', kind: 'series' },
  { id: 'PLTsG_ul83PKE', name: 'Philemon (2020)', kind: 'series' },
  { id: 'PLWLmfEoQLnBY', name: 'Visions of Hope in the Fire (2020)', kind: 'series' },
  { id: 'PLcVnilxMSYGIJ9kSij-mS2W-eMB-ShIyc', name: 'Coffee Met Bagel - Relationship Series', kind: 'series' },
  { id: 'PLVKPZdhxtwf0', name: 'Consecrate (January 2023)', kind: 'series' },
  { id: 'PLEEZHSXW_DOs', name: 'Consecrate (January 2024)', kind: 'series' },
  { id: 'PLJd9DrfRRU6I', name: 'Consecrate (January 2025)', kind: 'series' },
  { id: 'PLMxfLl6LX2oc', name: 'Consecrate (January 2026)', kind: 'series' },
  { id: 'PLcVnilxMSYGKQFAS8xgW0HhCZ8CVwWULL', name: 'Devotional Series', kind: 'series' },
  { id: 'PLcVnilxMSYGJvNAPRGXzi32iLlTjfa7M8', name: 'Ministry Magnified', kind: 'series' },
  { id: 'PLcVnilxMSYGINcBu-kvqP7vsZr36fbcIY', name: 'Mosaic Community', kind: 'series' },
]
